### PR TITLE
Require at least Ruby 2.2

### PR DESCRIPTION
**Pull request by tas50**
This brings chefstyle inline with our other projects.

Signed-off-by: Tim Smith <tsmith@chef.io>

### CODE REVIEW

**Comment by tas50** [comment]
Travis hasn't run for 6 months. I nuked the integration and added it again, but it's still not running. I'm not sure what's up with that.

**Comment by lamont-granquist** [comment]
specs have never worked

i don't really use them, criteria for merging is to not break chef/chef

**Comment by thommay** [comment]
I see no reason for ChefStyle not to be on ruby 2.3, really.

**Comment by lamont-granquist** [comment]
chef/chef still supports 2.2 so >2.3-only syntax still isn't allowed.

although EOL for 2.2 is likely months away, but i don't think its been formally announced yet.

**Comment by thommay** [comment]
I think 13 should be 2.3 only.

**Comment by tas50** [comment]
We should make it 2.3 when 13 ships. This gets us one step closer to that.

**Comment by tas50** [comment]
and by that I mean 2.3 syntax

**Pull request merged**
